apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  rules:
  - host: ihar.ratner.com
    http:
      paths:
        - path: /
          backend:
            serviceName: nginx-load-balancer
            servicePort: 80
  - host: ratner.ihar.com
    http:
      paths:
        - path: /
          backend:
            serviceName: apache-load-balancer
            servicePort: 80
