apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancer
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31111
      name: http
